[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://sunsolar-stock.onrender.com/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
